// redux/types/actionTypes.js
export const FETCH_CAREERS_REQUEST = 'FETCH_CAREERS_REQUEST';
export const FETCH_CAREERS_SUCCESS = 'FETCH_CAREERS_SUCCESS';
export const FETCH_CAREERS_FAILURE = 'FETCH_CAREERS_FAILURE';
