// redux/types/actionTypes.js
export const FETCH_CAREERS_REQUEST = 'FETCH_CAREERS_REQUEST';
export const FETCH_CAREERS_SUCCESS = 'FETCH_CAREERS_SUCCESS';
export const FETCH_CAREERS_FAILURE = 'FETCH_CAREERS_FAILURE';

export const FETCH_INSIGHTS_REQUEST = 'FETCH_INSIGHTS_REQUEST';
export const FETCH_INSIGHTS_SUCCESS = 'FETCH_INSIGHTS_SUCCESS';
export const FETCH_INSIGHTS_FAILURE = 'FETCH_INSIGHTS_FAILURE';
